### ISSUE TITLE
Make build_klein & runtest executable before submitting

### ISSUE THREAD

**Issue by hilliardj** [justiceadamsUNI/Klein-Compiler#34]
Wallingford:
     * Can you +x build_klein and runtest.sh before submitting?  That
       would be very helpful

**Comment by hilliardj** [comment]
I have set up a script to build the zip file on linux command line, so we will just need to make sure that we chmod it before zipping.  Let me know thoughts on including this script with our submissions, or if it is just a tool I can keep in my student.cs.

**Comment by justiceadamsUNI** [comment]
We decided to just manually do this before submission to wallingford
