### ISSUE TITLE
Error Messages 1

### ISSUE THREAD

**Issue by hilliardj** [justiceadamsUNI/Klein-Compiler#35]
Wallingford:
       * Showing the current token (or more) might help the programmer find
         the error even on a non-terminal error:

           No Rule exist in the Parse Table for (FACTOR_ID_TAIL,
           IDENTIFIER_LITERAL) near:
              FOO b)

         Oh, and "No rule exist_s_ in the parse table for..."

**Comment by justiceadamsUNI** [comment]
I don't understand this so I'm leaving it open as of project 3s submission
