### ISSUE TITLE
README

### ISSUE THREAD

**Issue by hilliardj** [justiceadamsUNI/Klein-Compiler#37]
Wallingford:
     * in README

         | -p or --kleinp:  This will build an executible file named kleinp ...
         | -f or --kleinp: Functionality coming soon!

       The first should say "-f or --kleinf" and the second, "-p or --kleinp".
       And "execut_a_ble".

**Comment by hilliardj** [comment]
Russell addressed this for the actual program, it was just not updated with the README.  And I need to learn how to spelld.

**Comment by harshavarmak** [comment]
Fixed
